using Microsoft.EntityFrameworkCore;
using Planova.Application.Dto;
using Planova.Application.Mappings;
using Planova.Application.Services;
using Planova.Persistence.DbContext;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Planova.Persistence.Services;

public class ReportService : IReportService
{
    private readonly PlanovaDbContext _context;

    public ReportService(PlanovaDbContext context)
    {
        _context = context;
    }

    public async Task<IEnumerable<ProjectSummaryDto>> GetProjectSummaryAsync(CancellationToken ct = default)
    {
        return await _context.Projects
            .Include(p => p.Client)
            .OrderBy(p => p.Code)
            .Select(p => p.ToSummaryDto())
            .ToListAsync(ct);
    }

    public async Task<IEnumerable<ClientSummaryDto>> GetClientSummaryAsync(CancellationToken ct = default)
    {
        return await _context.Clients
            .Include(c => c.Projects)
            .OrderBy(c => c.Name)
            .Select(c => new ClientSummaryDto(
                c.Id,
                c.Code,
                c.Name,
                c.ContactEmail,
                c.Projects.Count,
                c.UpdatedAt
            ))
            .ToListAsync(ct);
    }

    public async Task<IEnumerable<ContractSummaryDto>> GetContractSummaryAsync(CancellationToken ct = default)
    {
        return await _context.Contracts
            .Include(c => c.Project)
            .Include(c => c.Client)
            .OrderBy(c => c.Number)
            .Select(c => c.ToSummaryDto())
            .ToListAsync(ct);
    }

    public async Task<byte[]> ExportProjectsPdfAsync(CancellationToken ct = default)
    {
        var projects = await GetProjectSummaryAsync(ct);
        var headers = new[] { "Code", "Name", "Status", "Client", "Start Date", "Updated" };
        var rows = projects.Select(p => new[]
        {
            p.Code, p.Name, p.Status, p.ClientName ?? "-",
            p.StartDate?.ToString("d") ?? "-", p.UpdatedAt.ToString("g")
        }).ToList();

        return BuildPdf("Projects Report", headers, rows);
    }

    public async Task<byte[]> ExportClientsPdfAsync(CancellationToken ct = default)
    {
        var clients = await GetClientSummaryAsync(ct);
        var headers = new[] { "Code", "Name", "Email", "Projects", "Updated" };
        var rows = clients.Select(c => new[]
        {
            c.Code, c.Name, c.ContactEmail ?? "-",
            c.ProjectCount.ToString(), c.UpdatedAt.ToString("g")
        }).ToList();

        return BuildPdf("Clients Report", headers, rows);
    }

    public async Task<byte[]> ExportContractsPdfAsync(CancellationToken ct = default)
    {
        var contracts = await GetContractSummaryAsync(ct);
        var headers = new[] { "Number", "Title", "Value", "Project", "Client", "Updated" };
        var rows = contracts.Select(c => new[]
        {
            c.Number, c.Title, c.Value?.ToString("C") ?? "-",
            c.ProjectName ?? "-", c.ClientName ?? "-", c.UpdatedAt.ToString("g")
        }).ToList();

        return BuildPdf("Contracts Report", headers, rows);
    }

    private static byte[] BuildPdf(string title, string[] headers, List<string[]> rows)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(20);
                page.Size(PageSizes.A4.Landscape());
                page.Header().Text(title).FontSize(18).Bold();
                page.Content().Table(table =>
                {
                    table.ColumnsDefinition(cols =>
                    {
                        foreach (var _ in headers)
                            cols.RelativeColumn();
                    });

                    table.Header(header =>
                    {
                        foreach (var h in headers)
                            header.Cell().Background(Colors.Grey.Lighten3).Padding(4).Text(h).Bold().FontSize(9);
                    });

                    foreach (var row in rows)
                        foreach (var cell in row)
                            table.Cell().BorderBottom(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(4).Text(cell).FontSize(8);
                });
                page.Footer().AlignCenter().Text(t =>
                    t.Span("Generated by Planova").FontSize(8).FontColor(Colors.Grey.Medium));
            });
        }).GeneratePdf();
    }
}
